[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/tickets"
  to = "https://community.cncf.io/events/details/cncf-kcd-istanbul-presents-kcd-istanbul-2026/"
  status = 302
  force = true
